### ISSUE TITLE
No multiple edit

### ISSUE THREAD

**Issue by movingline** [Tastaturberuf/contao-image-copyright-bundle#3]
First, nice plugin!
Files cannot be edited with "multiple edit". No fields are visable.

![1](https://user-images.githubusercontent.com/28843579/127874874-d7b4ab63-c377-4442-956b-dad1fe9add6b.png)
![2](https://user-images.githubusercontent.com/28843579/127874915-0479961d-47c6-43a1-be23-aa12f4724291.png)

**Comment by Tastaturberuf** [comment]
which Contao version?

movingline ***@***.***> schrieb am Mo., 2. Aug. 2021, 16:10:

**Comment by movingline** [comment]
Contao Version 4.9.12

**Comment by Tastaturberuf** [comment]
I can this reproduce. I will have a look. thanks for the feedback.

**Comment by Tastaturberuf** [comment]
Fixed in 1.0.6 Thanks @movingline 

But: The backend show fields to **all files** and directories. This is a technical issue in the Contao core. Copyright hints on invalid image types or directories have no impact to the frondend module.

**Comment by movingline** [comment]
It works perfect! Thanks!
