### ISSUE TITLE
Not working with fileextensions in capital letters

### ISSUE THREAD

**Issue by werph** [Tastaturberuf/contao-image-copyright-bundle#5]
First of all thanks for this great extension.

I am not that into github yet. I hope, I am doing this right.

I'm using the extension for the first time and from time to time I had the problem that the Copyright-Fields are not displayed in the backend. After various assumptions and tests it turned out that capital fileextensions (in my case JPG) lead to the missing fields.
The very same file and filename with small extenion works fine.

Contao 4.9.25
PHP 7.4.26

**Comment by Tastaturberuf** [comment]
I think that is a valid bug. i fix this ASAP. thank you for the report.

**Comment by werph** [comment]
As temporary workaround without uploading a new file with small extension it is possible to use the multiple edit to store the copyright-info. the frontend module shows the info as expected.

**Comment by Tastaturberuf** [comment]
thanks @werph

**Comment by Tastaturberuf** [comment]
Fixed in 1.1.1
