### ISSUE TITLE
DcaFileListener: strtolower expects parameter 1 to be string, null given

### ISSUE THREAD

**Issue by Xirdion** [Tastaturberuf/contao-image-copyright-bundle#7]
Hi there. We encountered an issue while you using your bundle.
Within the EventListener **DcaFileListener** on line 109 there could be an error.

```php
pathinfo((string) $dc->id)['extension'];
```

When uploading a new image, this will have null as value.
So strtolower function will throw an error.

```php
\strtolower(pathinfo((string) $dc->id)['extension']);
```

I have added a workaround for our project:

```php
$path = pathinfo((string) $dc->id)['extension'];
$fileExtension = $path ? \strtolower($path) : '';
```

**Comment by Tastaturberuf** [comment]
Thank your for the report.

Want you make a PR?

**Comment by Xirdion** [comment]
Yes I will do a PR.
Is my suggested solution acceptable?

**Comment by Tastaturberuf** [comment]
if it works: yes 👍🏻

**Comment by Xirdion** [comment]
@Tastaturberuf created the PR #8 for this issue.

**Comment by Tastaturberuf** [comment]
Fixed in https://github.com/Tastaturberuf/contao-image-copyright-bundle/commit/601f3d7d2385fb0621d69e42dcfed29c0a5c9bfe 

thanks a lot
